config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Simple Airbnb</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>description</th>
      <th>price_per_night</th>
      <th>number_of_guests</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.name %></td>
        <td><%= flat.address %></td>
        <td><%= flat.description %></td>
        <td><%= flat.price_per_night %></td>
        <td><%= flat.number_of_guests %></td>
        <td><%= link_to 'Show', flat %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New flat', new_flat_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>